camel:
  springboot:
    name: formation-apache-camel

server:
  port: 0

# IN
in:
  directory: /Users/skouandongui/DEV/indata/ # dossier de dépot de fichier
  file:
    filemask: .*.[json|JSON]


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27017
      database: shopetl



